class SeedMovement {
  const SeedMovement({
    required this.id,
    required this.name,
    required this.category,
    required this.difficulty,
    required this.description,
    required this.xpToUnlock,
    required this.baseXp,
    required this.xpPerRep,
    required this.xpPerSecond,
    required this.sortOrder,
  });

  final String id;
  final String name;
  final String category;
  final int difficulty;
  final String description;
  final int xpToUnlock;

  final int baseXp;
  final int xpPerRep;
  final int xpPerSecond;

  final int sortOrder;
}

class SeedPrereq {
  const SeedPrereq({
    required this.movementId,
    required this.prereqMovementId,
    required this.prereqType,
  });

  final String movementId;
  final String prereqMovementId;

  // "unlocked" | "progress" | "bronze" | "silver" | "gold" | "mastered"
  final String prereqType;
}

const List<SeedMovement> seedMovements = [
  // =========================
  // MOBILITY / PREHAB
  // =========================
  SeedMovement(
    id: "wrist_mobility",
    name: "Wrist Mobility",
    category: "mobility",
    difficulty: 1,
    description:
        "Wrist prep for handstands/planche. Slow circles and lean pulses.",
    xpToUnlock: 0,
    baseXp: 4,
    xpPerRep: 0,
    xpPerSecond: 1,
    sortOrder: 10,
  ),
  SeedMovement(
    id: "shoulder_dislocates",
    name: "Shoulder Dislocates",
    category: "mobility",
    difficulty: 1,
    description:
        "Band/broom dislocates for overhead range and shoulder health.",
    xpToUnlock: 0,
    baseXp: 4,
    xpPerRep: 1,
    xpPerSecond: 0,
    sortOrder: 20,
  ),
  SeedMovement(
    id: "thoracic_extension",
    name: "Thoracic Extension",
    category: "mobility",
    difficulty: 1,
    description: "Upper back extension drills for overhead/bridge positions.",
    xpToUnlock: 0,
    baseXp: 4,
    xpPerRep: 0,
    xpPerSecond: 1,
    sortOrder: 30,
  ),
  SeedMovement(
    id: "hamstring_mobility",
    name: "Hamstring Mobility",
    category: "mobility",
    difficulty: 1,
    description: "Pike stretching and nerve-friendly hamstring work.",
    xpToUnlock: 0,
    baseXp: 4,
    xpPerRep: 0,
    xpPerSecond: 1,
    sortOrder: 40,
  ),
  SeedMovement(
    id: "ankle_mobility",
    name: "Ankle Mobility",
    category: "mobility",
    difficulty: 1,
    description: "Dorsiflexion work for deeper squats and cleaner landings.",
    xpToUnlock: 0,
    baseXp: 4,
    xpPerRep: 0,
    xpPerSecond: 1,
    sortOrder: 45,
  ),
  SeedMovement(
    id: "hip_flexor_mobility",
    name: "Hip Flexor Mobility",
    category: "mobility",
    difficulty: 1,
    description: "Front-line hip opening for squats, bridges, and split lines.",
    xpToUnlock: 0,
    baseXp: 4,
    xpPerRep: 0,
    xpPerSecond: 1,
    sortOrder: 47,
  ),
  SeedMovement(
    id: "pancake_stretch",
    name: "Pancake Stretch",
    category: "mobility",
    difficulty: 2,
    description: "Straddle flexibility for V-sit/press handstand progressions.",
    xpToUnlock: 150,
    baseXp: 5,
    xpPerRep: 0,
    xpPerSecond: 2,
    sortOrder: 50,
  ),
  SeedMovement(
    id: "couch_stretch",
    name: "Couch Stretch",
    category: "mobility",
    difficulty: 2,
    description: "Quad and hip-flexor stretch for upright squats and bridges.",
    xpToUnlock: 150,
    baseXp: 5,
    xpPerRep: 0,
    xpPerSecond: 2,
    sortOrder: 55,
  ),
  SeedMovement(
    id: "bridge_prep",
    name: "Bridge Prep",
    category: "mobility",
    difficulty: 2,
    description: "Wall shoulder opens and thoracic prep for bridge work.",
    xpToUnlock: 150,
    baseXp: 5,
    xpPerRep: 0,
    xpPerSecond: 2,
    sortOrder: 60,
  ),
  SeedMovement(
    id: "cossack_squat_mobility",
    name: "Cossack Squat Mobility",
    category: "mobility",
    difficulty: 3,
    description: "Lateral squat pattern to open adductors, hips, and ankles.",
    xpToUnlock: 350,
    baseXp: 6,
    xpPerRep: 3,
    xpPerSecond: 0,
    sortOrder: 65,
  ),
  SeedMovement(
    id: "bridge",
    name: "Bridge",
    category: "mobility",
    difficulty: 3,
    description: "Full bridge hold. Keep arms straight, breathe, control.",
    xpToUnlock: 350,
    baseXp: 6,
    xpPerRep: 0,
    xpPerSecond: 3,
    sortOrder: 70,
  ),

  // =========================
  // CORE / FOUNDATION
  // =========================
  SeedMovement(
    id: "plank",
    name: "Plank",
    category: "core",
    difficulty: 1,
    description: "Brace hard. Ribs down, glutes tight, neutral neck.",
    xpToUnlock: 0,
    baseXp: 5,
    xpPerRep: 0,
    xpPerSecond: 1,
    sortOrder: 110,
  ),
  SeedMovement(
    id: "side_plank",
    name: "Side Plank",
    category: "core",
    difficulty: 2,
    description: "Oblique strength. Keep hips stacked and glutes tight.",
    xpToUnlock: 150,
    baseXp: 6,
    xpPerRep: 0,
    xpPerSecond: 2,
    sortOrder: 115,
  ),
  SeedMovement(
    id: "hollow_hold",
    name: "Hollow Hold",
    category: "core",
    difficulty: 2,
    description: "Posterior pelvic tilt. Low back stays down.",
    xpToUnlock: 150,
    baseXp: 6,
    xpPerRep: 0,
    xpPerSecond: 2,
    sortOrder: 120,
  ),
  SeedMovement(
    id: "arch_hold",
    name: "Arch Hold",
    category: "core",
    difficulty: 2,
    description: "Posterior chain engagement. Great for pulling/levers.",
    xpToUnlock: 150,
    baseXp: 6,
    xpPerRep: 0,
    xpPerSecond: 2,
    sortOrder: 130,
  ),
  SeedMovement(
    id: "hanging_knee_raise",
    name: "Hanging Knee Raise",
    category: "core",
    difficulty: 3,
    description: "Control the swing. Knees to chest.",
    xpToUnlock: 350,
    baseXp: 10,
    xpPerRep: 4,
    xpPerSecond: 0,
    sortOrder: 140,
  ),
  SeedMovement(
    id: "hanging_leg_raise",
    name: "Hanging Leg Raise",
    category: "core",
    difficulty: 4,
    description: "Straight legs, no swing. Strong compression.",
    xpToUnlock: 650,
    baseXp: 12,
    xpPerRep: 5,
    xpPerSecond: 0,
    sortOrder: 150,
  ),
  SeedMovement(
    id: "toes_to_bar",
    name: "Toes-to-Bar",
    category: "core",
    difficulty: 5,
    description: "High core strength. Keep it controlled.",
    xpToUnlock: 900,
    baseXp: 14,
    xpPerRep: 6,
    xpPerSecond: 0,
    sortOrder: 160,
  ),
  SeedMovement(
    id: "tuck_l_sit",
    name: "Tuck L-Sit (Hold)",
    category: "core",
    difficulty: 3,
    description: "Support + compression. Keep shoulders active.",
    xpToUnlock: 350,
    baseXp: 10,
    xpPerRep: 0,
    xpPerSecond: 3,
    sortOrder: 170,
  ),
  SeedMovement(
    id: "l_sit",
    name: "L-Sit (Hold)",
    category: "core",
    difficulty: 4,
    description: "Full L-sit hold. Locked elbows and active shoulders.",
    xpToUnlock: 650,
    baseXp: 12,
    xpPerRep: 0,
    xpPerSecond: 4,
    sortOrder: 180,
  ),
  SeedMovement(
    id: "v_sit",
    name: "V-Sit (Hold)",
    category: "core",
    difficulty: 6,
    description: "Compression + flexibility. A big skill milestone.",
    xpToUnlock: 1200,
    baseXp: 16,
    xpPerRep: 0,
    xpPerSecond: 5,
    sortOrder: 190,
  ),
  SeedMovement(
    id: "hanging_oblique_raise",
    name: "Hanging Oblique Raise",
    category: "core",
    difficulty: 5,
    description: "Knees/legs to the side. Control the twist.",
    xpToUnlock: 900,
    baseXp: 14,
    xpPerRep: 6,
    xpPerSecond: 0,
    sortOrder: 195,
  ),
  SeedMovement(
    id: "hanging_windshield_wiper",
    name: "Hanging Windshield Wipers",
    category: "core",
    difficulty: 6,
    description: "Advanced obliques. No swing, slow arcs side-to-side.",
    xpToUnlock: 1200,
    baseXp: 16,
    xpPerRep: 7,
    xpPerSecond: 0,
    sortOrder: 198,
  ),

  // Dragon flag line
  SeedMovement(
    id: "tuck_dragon_flag",
    name: "Tuck Dragon Flag",
    category: "core",
    difficulty: 6,
    description: "Tucked body. Control the lever and keep hips locked.",
    xpToUnlock: 900,
    baseXp: 16,
    xpPerRep: 6,
    xpPerSecond: 0,
    sortOrder: 200,
  ),
  SeedMovement(
    id: "dragon_flag_negative",
    name: "Dragon Flag Negative",
    category: "core",
    difficulty: 7,
    description: "Start high, lower slowly. No bending at the hips.",
    xpToUnlock: 1200,
    baseXp: 18,
    xpPerRep: 0,
    xpPerSecond: 4,
    sortOrder: 205,
  ),
  SeedMovement(
    id: "dragon_flag",
    name: "Dragon Flag",
    category: "core",
    difficulty: 8,
    description: "Full dragon flag reps. Brutal core and body tension.",
    xpToUnlock: 1600,
    baseXp: 20,
    xpPerRep: 8,
    xpPerSecond: 0,
    sortOrder: 210,
  ),

  // Press handstand compression line
  SeedMovement(
    id: "pike_compression",
    name: "Pike Compression (Seated)",
    category: "core",
    difficulty: 4,
    description: "Lift heels off the floor in a pike. Builds press strength.",
    xpToUnlock: 350,
    baseXp: 12,
    xpPerRep: 3,
    xpPerSecond: 0,
    sortOrder: 215,
  ),
  SeedMovement(
    id: "seated_pike_lift",
    name: "Seated Pike Lift",
    category: "core",
    difficulty: 5,
    description: "Hands by hips, lift both legs. Keep shoulders depressed.",
    xpToUnlock: 650,
    baseXp: 14,
    xpPerRep: 4,
    xpPerSecond: 0,
    sortOrder: 220,
  ),
  SeedMovement(
    id: "straddle_compression",
    name: "Straddle Compression Lift",
    category: "core",
    difficulty: 6,
    description: "Straddle leg lifts. Strong carryover to straddle press.",
    xpToUnlock: 900,
    baseXp: 16,
    xpPerRep: 5,
    xpPerSecond: 0,
    sortOrder: 225,
  ),

  // =========================
  // PUSH
  // =========================
  SeedMovement(
    id: "incline_push_up",
    name: "Incline Push-up",
    category: "push",
    difficulty: 1,
    description: "Hands elevated. Build pressing strength and control.",
    xpToUnlock: 0,
    baseXp: 5,
    xpPerRep: 2,
    xpPerSecond: 0,
    sortOrder: 2100,
  ),
  SeedMovement(
    id: "knee_push_up",
    name: "Knee Push-up",
    category: "push",
    difficulty: 1,
    description: "Push-up regression focusing on full range and form.",
    xpToUnlock: 50,
    baseXp: 5,
    xpPerRep: 2,
    xpPerSecond: 0,
    sortOrder: 2110,
  ),
  SeedMovement(
    id: "push_up",
    name: "Push-up",
    category: "push",
    difficulty: 2,
    description: "Classic horizontal press. Core tight, full lockout.",
    xpToUnlock: 150,
    baseXp: 8,
    xpPerRep: 3,
    xpPerSecond: 0,
    sortOrder: 2120,
  ),
  SeedMovement(
    id: "diamond_push_up",
    name: "Diamond Push-up",
    category: "push",
    difficulty: 3,
    description: "Triceps bias. Great carryover to dips and pressing.",
    xpToUnlock: 350,
    baseXp: 10,
    xpPerRep: 4,
    xpPerSecond: 0,
    sortOrder: 2130,
  ),
  SeedMovement(
    id: "decline_push_up",
    name: "Decline Push-up",
    category: "push",
    difficulty: 3,
    description: "More shoulder load. Strong step toward HSPU work.",
    xpToUnlock: 350,
    baseXp: 10,
    xpPerRep: 4,
    xpPerSecond: 0,
    sortOrder: 2140,
  ),
  SeedMovement(
    id: "archer_push_up",
    name: "Archer Push-up",
    category: "push",
    difficulty: 4,
    description: "Unilateral pressing strength. Control the shift.",
    xpToUnlock: 650,
    baseXp: 12,
    xpPerRep: 5,
    xpPerSecond: 0,
    sortOrder: 2150,
  ),
  SeedMovement(
    id: "pseudo_planche_push_up",
    name: "Pseudo Planche Push-up",
    category: "push",
    difficulty: 5,
    description: "Planche-lean push-ups. Strong planche builder.",
    xpToUnlock: 900,
    baseXp: 14,
    xpPerRep: 6,
    xpPerSecond: 0,
    sortOrder: 2160,
  ),
  SeedMovement(
    id: "support_hold",
    name: "Support Hold (Bars/Rings)",
    category: "push",
    difficulty: 2,
    description: "Lockout support. Active shoulders and core tight.",
    xpToUnlock: 150,
    baseXp: 8,
    xpPerRep: 0,
    xpPerSecond: 2,
    sortOrder: 2170,
  ),
  SeedMovement(
    id: "parallel_dip",
    name: "Parallel Bar Dip",
    category: "push",
    difficulty: 3,
    description: "Full dips with clean lockout and shoulder control.",
    xpToUnlock: 350,
    baseXp: 12,
    xpPerRep: 5,
    xpPerSecond: 0,
    sortOrder: 2180,
  ),
  SeedMovement(
    id: "pike_push_up",
    name: "Pike Push-up",
    category: "push",
    difficulty: 3,
    description: "Shoulder-focused press. Hips high, head to floor.",
    xpToUnlock: 350,
    baseXp: 10,
    xpPerRep: 4,
    xpPerSecond: 0,
    sortOrder: 2200,
  ),
  SeedMovement(
    id: "elevated_pike_push_up",
    name: "Elevated Pike Push-up",
    category: "push",
    difficulty: 4,
    description: "More vertical pressing. Big HSPU prep.",
    xpToUnlock: 650,
    baseXp: 12,
    xpPerRep: 5,
    xpPerSecond: 0,
    sortOrder: 2210,
  ),

  // =========================
  // PULL
  // =========================
  SeedMovement(
    id: "active_hang",
    name: "Active Hang",
    category: "pull",
    difficulty: 1,
    description: "Hang with shoulders active (scap engaged).",
    xpToUnlock: 0,
    baseXp: 5,
    xpPerRep: 0,
    xpPerSecond: 1,
    sortOrder: 3100,
  ),
  SeedMovement(
    id: "scap_pull_up",
    name: "Scapular Pull-up",
    category: "pull",
    difficulty: 1,
    description: "Small pull focusing on scapular depression/retraction.",
    xpToUnlock: 0,
    baseXp: 5,
    xpPerRep: 1,
    xpPerSecond: 0,
    sortOrder: 3110,
  ),
  SeedMovement(
    id: "australian_pull_up",
    name: "Australian Row",
    category: "pull",
    difficulty: 1,
    description: "Body row. Build pulling strength for pull-ups.",
    xpToUnlock: 0,
    baseXp: 6,
    xpPerRep: 2,
    xpPerSecond: 0,
    sortOrder: 3120,
  ),
  SeedMovement(
    id: "negative_pull_up",
    name: "Negative Pull-up",
    category: "pull",
    difficulty: 3,
    description: "Jump to top, lower slowly with control.",
    xpToUnlock: 250,
    baseXp: 10,
    xpPerRep: 4,
    xpPerSecond: 0,
    sortOrder: 3130,
  ),
  SeedMovement(
    id: "chin_up",
    name: "Chin-up",
    category: "pull",
    difficulty: 3,
    description: "Strict chin-ups. Full range, no swing.",
    xpToUnlock: 350,
    baseXp: 11,
    xpPerRep: 4,
    xpPerSecond: 0,
    sortOrder: 3140,
  ),
  SeedMovement(
    id: "pull_up",
    name: "Pull-up",
    category: "pull",
    difficulty: 4,
    description: "Full pull-up. Chest up, no swinging.",
    xpToUnlock: 450,
    baseXp: 12,
    xpPerRep: 5,
    xpPerSecond: 0,
    sortOrder: 3150,
  ),
  SeedMovement(
    id: "explosive_pull_up",
    name: "Explosive Pull-up",
    category: "pull",
    difficulty: 5,
    description: "Pull high and fast. Bridges to muscle-up.",
    xpToUnlock: 900,
    baseXp: 14,
    xpPerRep: 6,
    xpPerSecond: 0,
    sortOrder: 3160,
  ),

  // One-arm pull-up progression
  SeedMovement(
    id: "archer_pull_up",
    name: "Archer Pull-up",
    category: "pull",
    difficulty: 6,
    description: "Pull mostly to one side. Strong one-arm builder.",
    xpToUnlock: 900,
    baseXp: 16,
    xpPerRep: 6,
    xpPerSecond: 0,
    sortOrder: 3170,
  ),
  SeedMovement(
    id: "typewriter_pull_up",
    name: "Typewriter Pull-up",
    category: "pull",
    difficulty: 7,
    description: "Hold high and move side-to-side. Control the transition.",
    xpToUnlock: 1200,
    baseXp: 18,
    xpPerRep: 7,
    xpPerSecond: 0,
    sortOrder: 3180,
  ),
  SeedMovement(
    id: "uneven_pull_up",
    name: "Uneven Pull-up",
    category: "pull",
    difficulty: 7,
    description: "One hand lower. Builds unilateral strength safely.",
    xpToUnlock: 1600,
    baseXp: 18,
    xpPerRep: 7,
    xpPerSecond: 0,
    sortOrder: 3190,
  ),
  SeedMovement(
    id: "one_arm_hang",
    name: "One-arm Hang (Hold)",
    category: "pull",
    difficulty: 6,
    description: "Shoulder packed. Build grip and connective tissue tolerance.",
    xpToUnlock: 900,
    baseXp: 16,
    xpPerRep: 0,
    xpPerSecond: 4,
    sortOrder: 3200,
  ),
  SeedMovement(
    id: "one_arm_lockoff",
    name: "One-arm Lock-off (Hold)",
    category: "pull",
    difficulty: 8,
    description: "Hold at top/mid. Massive strength milestone.",
    xpToUnlock: 2100,
    baseXp: 20,
    xpPerRep: 0,
    xpPerSecond: 5,
    sortOrder: 3210,
  ),
  SeedMovement(
    id: "one_arm_negative_pull_up",
    name: "One-arm Pull-up Negative",
    category: "pull",
    difficulty: 9,
    description: "Start high, lower slowly on one arm. Very demanding.",
    xpToUnlock: 2800,
    baseXp: 22,
    xpPerRep: 0,
    xpPerSecond: 6,
    sortOrder: 3220,
  ),
  SeedMovement(
    id: "one_arm_pull_up",
    name: "One-arm Pull-up",
    category: "pull",
    difficulty: 10,
    description: "Full one-arm pull-up. Elite pulling strength.",
    xpToUnlock: 3600,
    baseXp: 26,
    xpPerRep: 10,
    xpPerSecond: 0,
    sortOrder: 3230,
  ),

  // =========================
  // LEGS
  // =========================
  SeedMovement(
    id: "bodyweight_squat",
    name: "Bodyweight Squat",
    category: "legs",
    difficulty: 1,
    description: "Knees track toes. Depth and control.",
    xpToUnlock: 0,
    baseXp: 5,
    xpPerRep: 2,
    xpPerSecond: 0,
    sortOrder: 4100,
  ),
  SeedMovement(
    id: "split_squat",
    name: "Split Squat",
    category: "legs",
    difficulty: 2,
    description: "Single-leg strength and balance builder.",
    xpToUnlock: 150,
    baseXp: 8,
    xpPerRep: 3,
    xpPerSecond: 0,
    sortOrder: 4110,
  ),
  SeedMovement(
    id: "reverse_lunge",
    name: "Reverse Lunge",
    category: "legs",
    difficulty: 2,
    description: "Knee-friendly unilateral work for strength and control.",
    xpToUnlock: 150,
    baseXp: 8,
    xpPerRep: 3,
    xpPerSecond: 0,
    sortOrder: 4115,
  ),
  SeedMovement(
    id: "bulgarian_split_squat",
    name: "Bulgarian Split Squat",
    category: "legs",
    difficulty: 3,
    description: "Rear-foot elevated. Big quad and glute builder.",
    xpToUnlock: 350,
    baseXp: 10,
    xpPerRep: 4,
    xpPerSecond: 0,
    sortOrder: 4120,
  ),
  SeedMovement(
    id: "cossack_squat",
    name: "Cossack Squat",
    category: "legs",
    difficulty: 3,
    description: "Deep lateral squat for strength, mobility, and control.",
    xpToUnlock: 350,
    baseXp: 10,
    xpPerRep: 4,
    xpPerSecond: 0,
    sortOrder: 4125,
  ),
  SeedMovement(
    id: "shrimp_squat",
    name: "Shrimp Squat",
    category: "legs",
    difficulty: 4,
    description: "Great pistol prep. Control knee and balance.",
    xpToUnlock: 650,
    baseXp: 12,
    xpPerRep: 5,
    xpPerSecond: 0,
    sortOrder: 4130,
  ),
  SeedMovement(
    id: "jump_squat",
    name: "Jump Squat",
    category: "legs",
    difficulty: 3,
    description: "Explosive squat pattern for power and landing mechanics.",
    xpToUnlock: 350,
    baseXp: 10,
    xpPerRep: 4,
    xpPerSecond: 0,
    sortOrder: 4135,
  ),
  SeedMovement(
    id: "shrimp_squat_negative",
    name: "Shrimp Squat Negative",
    category: "legs",
    difficulty: 4,
    description:
        "Controlled eccentric single-leg strength for shrimp progress.",
    xpToUnlock: 650,
    baseXp: 12,
    xpPerRep: 3,
    xpPerSecond: 0,
    sortOrder: 4138,
  ),
  SeedMovement(
    id: "assisted_pistol_squat",
    name: "Assisted Pistol Squat",
    category: "legs",
    difficulty: 4,
    description: "Use support to build depth and strength.",
    xpToUnlock: 650,
    baseXp: 12,
    xpPerRep: 5,
    xpPerSecond: 0,
    sortOrder: 4140,
  ),
  SeedMovement(
    id: "pistol_squat",
    name: "Pistol Squat",
    category: "legs",
    difficulty: 5,
    description: "Full single-leg squat. High skill and strength.",
    xpToUnlock: 700,
    baseXp: 15,
    xpPerRep: 8,
    xpPerSecond: 0,
    sortOrder: 4150,
  ),

  // =========================
  // SKILLS (HANDSTAND / LEVERS / MUSCLE-UP / FLAG / PLANCHE)
  // =========================
  SeedMovement(
    id: "wall_handstand",
    name: "Wall Handstand (Hold)",
    category: "skill",
    difficulty: 3,
    description: "Chest-to-wall. Stack shoulders, ribs down.",
    xpToUnlock: 350,
    baseXp: 10,
    xpPerRep: 0,
    xpPerSecond: 3,
    sortOrder: 5100,
  ),
  SeedMovement(
    id: "freestanding_handstand",
    name: "Freestanding Handstand",
    category: "skill",
    difficulty: 5,
    description: "Balance without the wall. Train shape and control.",
    xpToUnlock: 900,
    baseXp: 14,
    xpPerRep: 0,
    xpPerSecond: 4,
    sortOrder: 5110,
  ),
  SeedMovement(
    id: "wall_hspu_negative",
    name: "Wall Handstand Push-up Negative",
    category: "skill",
    difficulty: 6,
    description: "Controlled lowering. Builds strict HSPU.",
    xpToUnlock: 1200,
    baseXp: 16,
    xpPerRep: 0,
    xpPerSecond: 4,
    sortOrder: 5120,
  ),
  SeedMovement(
    id: "wall_hspu",
    name: "Wall Handstand Push-up",
    category: "skill",
    difficulty: 7,
    description: "Strict full range on wall. No kipping.",
    xpToUnlock: 1600,
    baseXp: 18,
    xpPerRep: 6,
    xpPerSecond: 0,
    sortOrder: 5130,
  ),

  // Press handstand progression
  SeedMovement(
    id: "tuck_press_handstand",
    name: "Tuck Press Handstand",
    category: "skill",
    difficulty: 7,
    description: "Press from tuck. Keep shoulders forward and compress hard.",
    xpToUnlock: 1600,
    baseXp: 18,
    xpPerRep: 2,
    xpPerSecond: 0,
    sortOrder: 5140,
  ),
  SeedMovement(
    id: "straddle_press_handstand",
    name: "Straddle Press Handstand",
    category: "skill",
    difficulty: 8,
    description: "Press from straddle. Big flexibility + strength demand.",
    xpToUnlock: 2100,
    baseXp: 20,
    xpPerRep: 2,
    xpPerSecond: 0,
    sortOrder: 5150,
  ),
  SeedMovement(
    id: "press_handstand",
    name: "Press Handstand",
    category: "skill",
    difficulty: 9,
    description: "Full press from pike. High-level control and compression.",
    xpToUnlock: 2800,
    baseXp: 22,
    xpPerRep: 2,
    xpPerSecond: 0,
    sortOrder: 5160,
  ),

  // Front lever holds + raises
  SeedMovement(
    id: "tuck_front_lever",
    name: "Tuck Front Lever (Hold)",
    category: "skill",
    difficulty: 6,
    description: "Hold tuck. Scapula depressed, hollow body.",
    xpToUnlock: 900,
    baseXp: 12,
    xpPerRep: 0,
    xpPerSecond: 4,
    sortOrder: 5200,
  ),
  SeedMovement(
    id: "adv_tuck_front_lever",
    name: "Advanced Tuck Front Lever (Hold)",
    category: "skill",
    difficulty: 7,
    description: "Harder tuck. Keep hips open and ribs down.",
    xpToUnlock: 1600,
    baseXp: 14,
    xpPerRep: 0,
    xpPerSecond: 4,
    sortOrder: 5210,
  ),
  SeedMovement(
    id: "straddle_front_lever",
    name: "Straddle Front Lever (Hold)",
    category: "skill",
    difficulty: 8,
    description: "Straddle lever. Donâ€™t pike, stay tight.",
    xpToUnlock: 2100,
    baseXp: 16,
    xpPerRep: 0,
    xpPerSecond: 5,
    sortOrder: 5220,
  ),
  SeedMovement(
    id: "front_lever",
    name: "Front Lever (Hold)",
    category: "skill",
    difficulty: 9,
    description: "Full front lever hold. Elite control and strength.",
    xpToUnlock: 2800,
    baseXp: 18,
    xpPerRep: 0,
    xpPerSecond: 6,
    sortOrder: 5230,
  ),
  SeedMovement(
    id: "tuck_front_lever_raises",
    name: "Tuck Front Lever Raises",
    category: "skill",
    difficulty: 7,
    description: "Dynamic lever strength. Control the arc without swinging.",
    xpToUnlock: 1600,
    baseXp: 18,
    xpPerRep: 6,
    xpPerSecond: 0,
    sortOrder: 5240,
  ),
  SeedMovement(
    id: "adv_tuck_front_lever_raises",
    name: "Advanced Tuck Front Lever Raises",
    category: "skill",
    difficulty: 8,
    description: "Harder raises. Keep scap depressed and ribs down.",
    xpToUnlock: 2100,
    baseXp: 20,
    xpPerRep: 7,
    xpPerSecond: 0,
    sortOrder: 5250,
  ),
  SeedMovement(
    id: "front_lever_raises",
    name: "Front Lever Raises",
    category: "skill",
    difficulty: 10,
    description: "Full lever raises. Elite dynamic strength.",
    xpToUnlock: 3600,
    baseXp: 26,
    xpPerRep: 10,
    xpPerSecond: 0,
    sortOrder: 5260,
  ),

  // Back lever line
  SeedMovement(
    id: "german_hang",
    name: "German Hang (Hold)",
    category: "skill",
    difficulty: 5,
    description: "Shoulder extension under load. Respect it.",
    xpToUnlock: 900,
    baseXp: 12,
    xpPerRep: 0,
    xpPerSecond: 3,
    sortOrder: 5300,
  ),
  SeedMovement(
    id: "skin_the_cat",
    name: "Skin the Cat",
    category: "skill",
    difficulty: 6,
    description: "Controlled rotation through German hang.",
    xpToUnlock: 1200,
    baseXp: 14,
    xpPerRep: 2,
    xpPerSecond: 0,
    sortOrder: 5310,
  ),
  SeedMovement(
    id: "tuck_back_lever",
    name: "Tuck Back Lever (Hold)",
    category: "skill",
    difficulty: 7,
    description: "Back lever tuck. Active shoulders and glutes.",
    xpToUnlock: 1600,
    baseXp: 16,
    xpPerRep: 0,
    xpPerSecond: 4,
    sortOrder: 5320,
  ),
  SeedMovement(
    id: "back_lever",
    name: "Back Lever (Hold)",
    category: "skill",
    difficulty: 8,
    description: "Full back lever hold. Shoulder + core strength.",
    xpToUnlock: 2100,
    baseXp: 18,
    xpPerRep: 0,
    xpPerSecond: 5,
    sortOrder: 5330,
  ),

  // Muscle-up line (bar)
  SeedMovement(
    id: "muscle_up_transition",
    name: "Muscle-up Transition",
    category: "skill",
    difficulty: 6,
    description: "Transition drill. Close to the bar, smooth turnover.",
    xpToUnlock: 1200,
    baseXp: 14,
    xpPerRep: 3,
    xpPerSecond: 0,
    sortOrder: 5400,
  ),
  SeedMovement(
    id: "bar_muscle_up",
    name: "Bar Muscle-up",
    category: "skill",
    difficulty: 7,
    description: "Explosive pull + fast transition to dip.",
    xpToUnlock: 1600,
    baseXp: 18,
    xpPerRep: 6,
    xpPerSecond: 0,
    sortOrder: 5410,
  ),

  // Human flag progression
  SeedMovement(
    id: "flag_pole_support",
    name: "Flag Pole Support (Hold)",
    category: "skill",
    difficulty: 7,
    description: "Pole support position. Shoulders packed, hips tight.",
    xpToUnlock: 1200,
    baseXp: 18,
    xpPerRep: 0,
    xpPerSecond: 4,
    sortOrder: 5500,
  ),
  SeedMovement(
    id: "tucked_human_flag",
    name: "Tucked Human Flag (Hold)",
    category: "skill",
    difficulty: 8,
    description: "Tucked flag hold. Focus on straight line from shoulders.",
    xpToUnlock: 1600,
    baseXp: 20,
    xpPerRep: 0,
    xpPerSecond: 5,
    sortOrder: 5510,
  ),
  SeedMovement(
    id: "adv_tuck_human_flag",
    name: "Advanced Tuck Human Flag (Hold)",
    category: "skill",
    difficulty: 9,
    description: "Harder tuck. Strong shoulder/oblique demand.",
    xpToUnlock: 2100,
    baseXp: 22,
    xpPerRep: 0,
    xpPerSecond: 6,
    sortOrder: 5520,
  ),
  SeedMovement(
    id: "straddle_human_flag",
    name: "Straddle Human Flag (Hold)",
    category: "skill",
    difficulty: 10,
    description: "Straddle lever. Control the hips and avoid rotation.",
    xpToUnlock: 2800,
    baseXp: 26,
    xpPerRep: 0,
    xpPerSecond: 7,
    sortOrder: 5530,
  ),
  SeedMovement(
    id: "human_flag",
    name: "Human Flag (Hold)",
    category: "skill",
    difficulty: 10,
    description: "Full human flag. Elite shoulder + core strength.",
    xpToUnlock: 3600,
    baseXp: 28,
    xpPerRep: 0,
    xpPerSecond: 8,
    sortOrder: 5540,
  ),

  // Planche progression
  SeedMovement(
    id: "planche_lean",
    name: "Planche Lean (Hold)",
    category: "skill",
    difficulty: 6,
    description: "Lean forward with protraction. Straight arms, scap active.",
    xpToUnlock: 900,
    baseXp: 16,
    xpPerRep: 0,
    xpPerSecond: 4,
    sortOrder: 5600,
  ),
  SeedMovement(
    id: "frog_stand",
    name: "Frog Stand (Hold)",
    category: "skill",
    difficulty: 6,
    description: "Entry balance + elbow shelf. Good early planche control.",
    xpToUnlock: 900,
    baseXp: 16,
    xpPerRep: 0,
    xpPerSecond: 4,
    sortOrder: 5610,
  ),
  SeedMovement(
    id: "tuck_planche",
    name: "Tuck Planche (Hold)",
    category: "skill",
    difficulty: 7,
    description: "Tucked planche hold. Protract hard, lock elbows.",
    xpToUnlock: 1600,
    baseXp: 20,
    xpPerRep: 0,
    xpPerSecond: 5,
    sortOrder: 5620,
  ),
  SeedMovement(
    id: "adv_tuck_planche",
    name: "Advanced Tuck Planche (Hold)",
    category: "skill",
    difficulty: 8,
    description: "Open the hips. Stay protracted and hollow.",
    xpToUnlock: 2100,
    baseXp: 22,
    xpPerRep: 0,
    xpPerSecond: 6,
    sortOrder: 5630,
  ),
  SeedMovement(
    id: "straddle_planche",
    name: "Straddle Planche (Hold)",
    category: "skill",
    difficulty: 9,
    description: "Straddle hold. Keep shoulders forward and elbows locked.",
    xpToUnlock: 2800,
    baseXp: 26,
    xpPerRep: 0,
    xpPerSecond: 7,
    sortOrder: 5640,
  ),
  SeedMovement(
    id: "planche",
    name: "Planche (Hold)",
    category: "skill",
    difficulty: 10,
    description: "Full planche hold. Elite straight-arm pushing strength.",
    xpToUnlock: 3600,
    baseXp: 28,
    xpPerRep: 0,
    xpPerSecond: 8,
    sortOrder: 5650,
  ),

  // =========================
  // COMPOUND TRANSITIONS
  // =========================
  SeedMovement(
    id: "l_sit_to_tuck_handstand",
    name: "L-Sit to Tuck Handstand",
    category: "compound",
    difficulty: 8,
    description:
        "From L-sit, compress and press into a tuck handstand with control.",
    xpToUnlock: 2100,
    baseXp: 20,
    xpPerRep: 2,
    xpPerSecond: 0,
    sortOrder: 5710,
  ),
  SeedMovement(
    id: "l_sit_to_handstand",
    name: "L-Sit to Handstand",
    category: "compound",
    difficulty: 9,
    description:
        "Press from L-sit into handstand without jump or momentum. Smooth and strict.",
    xpToUnlock: 2800,
    baseXp: 24,
    xpPerRep: 2,
    xpPerSecond: 0,
    sortOrder: 5720,
  ),
  SeedMovement(
    id: "v_sit_to_handstand",
    name: "V-Sit to Handstand",
    category: "compound",
    difficulty: 10,
    description:
        "Elite compression transition from V-sit into handstand with no kick.",
    xpToUnlock: 3600,
    baseXp: 28,
    xpPerRep: 2,
    xpPerSecond: 0,
    sortOrder: 5730,
  ),
  SeedMovement(
    id: "l_sit_to_tuck_planche",
    name: "L-Sit to Tuck Planche",
    category: "compound",
    difficulty: 8,
    description: "Transition from L-sit into tuck planche with no hop.",
    xpToUnlock: 2100,
    baseXp: 22,
    xpPerRep: 2,
    xpPerSecond: 0,
    sortOrder: 5740,
  ),
  SeedMovement(
    id: "tuck_planche_to_handstand",
    name: "Tuck Planche to Handstand",
    category: "compound",
    difficulty: 10,
    description:
        "Dynamic press from tuck planche into handstand. Straight-arm control.",
    xpToUnlock: 3600,
    baseXp: 30,
    xpPerRep: 1,
    xpPerSecond: 0,
    sortOrder: 5750,
  ),
  SeedMovement(
    id: "l_sit_to_muscle_up_transition",
    name: "L-Sit to Muscle-up Transition",
    category: "compound",
    difficulty: 9,
    description:
        "From high L-sit pull, transition into a clean bar muscle-up path.",
    xpToUnlock: 2800,
    baseXp: 24,
    xpPerRep: 2,
    xpPerSecond: 0,
    sortOrder: 5760,
  ),
  SeedMovement(
    id: "front_lever_to_muscle_up",
    name: "Front Lever to Muscle-up",
    category: "compound",
    difficulty: 10,
    description:
        "Explosive transition from front-lever strength into bar turnover.",
    xpToUnlock: 3600,
    baseXp: 30,
    xpPerRep: 2,
    xpPerSecond: 0,
    sortOrder: 5770,
  ),
  SeedMovement(
    id: "bar_muscle_up_to_handstand_negative",
    name: "Bar Muscle-up to Handstand Negative",
    category: "compound",
    difficulty: 10,
    description:
        "Control a slow negative from top support toward handstand line strength.",
    xpToUnlock: 4200,
    baseXp: 32,
    xpPerRep: 0,
    xpPerSecond: 4,
    sortOrder: 5780,
  ),

  // =========================
  // RINGS (BEGINNER -> ADVANCED) - EXPANDED
  // =========================
  SeedMovement(
    id: "ring_support_assisted",
    name: "Ring Support (Assisted Hold)",
    category: "rings",
    difficulty: 2,
    description:
        "Feet on floor or light band. Lock elbows, shoulders down, steady rings.",
    xpToUnlock: 150,
    baseXp: 8,
    xpPerRep: 0,
    xpPerSecond: 2,
    sortOrder: 6100,
  ),
  SeedMovement(
    id: "ring_support_scap_shrugs",
    name: "Ring Support Scap Shrugs",
    category: "rings",
    difficulty: 2,
    description:
        "Small range: depress/elevate scapula while staying locked out. Teaches control.",
    xpToUnlock: 150,
    baseXp: 8,
    xpPerRep: 2,
    xpPerSecond: 0,
    sortOrder: 6110,
  ),
  SeedMovement(
    id: "ring_support_hold",
    name: "Ring Support (Hold)",
    category: "rings",
    difficulty: 4,
    description:
        "Strict ring support. Elbows locked, rings still, body hollow.",
    xpToUnlock: 450,
    baseXp: 12,
    xpPerRep: 0,
    xpPerSecond: 3,
    sortOrder: 6120,
  ),
  SeedMovement(
    id: "ring_row",
    name: "Ring Row",
    category: "rings",
    difficulty: 2,
    description: "Body row on rings. Build pulling strength + stability.",
    xpToUnlock: 150,
    baseXp: 8,
    xpPerRep: 3,
    xpPerSecond: 0,
    sortOrder: 6130,
  ),
  SeedMovement(
    id: "ring_face_pull",
    name: "Ring Face Pull",
    category: "rings",
    difficulty: 3,
    description:
        "High row to face. Great scap/rear-delt control for ring stability.",
    xpToUnlock: 250,
    baseXp: 10,
    xpPerRep: 4,
    xpPerSecond: 0,
    sortOrder: 6140,
  ),
  SeedMovement(
    id: "ring_push_up",
    name: "Ring Push-up",
    category: "rings",
    difficulty: 3,
    description:
        "Unstable push-ups on rings. Keep rings close and control depth.",
    xpToUnlock: 250,
    baseXp: 10,
    xpPerRep: 4,
    xpPerSecond: 0,
    sortOrder: 6150,
  ),
  SeedMovement(
    id: "ring_pull_up",
    name: "Ring Pull-up",
    category: "rings",
    difficulty: 5,
    description:
        "Strict pull-ups on rings. Keep rings close and avoid swinging.",
    xpToUnlock: 900,
    baseXp: 14,
    xpPerRep: 6,
    xpPerSecond: 0,
    sortOrder: 6160,
  ),
  SeedMovement(
    id: "false_grip_hang",
    name: "False Grip Hang (Hold)",
    category: "rings",
    difficulty: 4,
    description:
        "Build false grip tolerance. Wrists over rings, shoulders packed.",
    xpToUnlock: 450,
    baseXp: 12,
    xpPerRep: 0,
    xpPerSecond: 3,
    sortOrder: 6170,
  ),
  SeedMovement(
    id: "false_grip_row",
    name: "False Grip Ring Row",
    category: "rings",
    difficulty: 5,
    description:
        "Rows using false grip. Huge carryover to strict ring muscle-up.",
    xpToUnlock: 650,
    baseXp: 14,
    xpPerRep: 5,
    xpPerSecond: 0,
    sortOrder: 6180,
  ),
  SeedMovement(
    id: "ring_l_sit_support",
    name: "Ring L-Sit (Support Hold)",
    category: "rings",
    difficulty: 6,
    description: "L-sit on rings. Tremendous stability + compression demand.",
    xpToUnlock: 1200,
    baseXp: 18,
    xpPerRep: 0,
    xpPerSecond: 5,
    sortOrder: 6185,
  ),
  SeedMovement(
    id: "ring_support_turnout_assisted",
    name: "Ring Support (Assisted RTO)",
    category: "rings",
    difficulty: 6,
    description:
        "Turn rings out with assistance (feet/band). Prep for full RTO support.",
    xpToUnlock: 900,
    baseXp: 16,
    xpPerRep: 0,
    xpPerSecond: 4,
    sortOrder: 6190,
  ),
  SeedMovement(
    id: "ring_support_rto",
    name: "Ring Support (RTO Hold)",
    category: "rings",
    difficulty: 7,
    description: "Rings turned out support. Lock elbows, active shoulders.",
    xpToUnlock: 1600,
    baseXp: 20,
    xpPerRep: 0,
    xpPerSecond: 5,
    sortOrder: 6200,
  ),
  SeedMovement(
    id: "ring_dip_negative",
    name: "Ring Dip Negative",
    category: "rings",
    difficulty: 5,
    description:
        "Start locked-out, lower slowly. Rings stay close; elbows track.",
    xpToUnlock: 650,
    baseXp: 14,
    xpPerRep: 0,
    xpPerSecond: 4,
    sortOrder: 6210,
  ),
  SeedMovement(
    id: "ring_dip",
    name: "Ring Dip",
    category: "rings",
    difficulty: 6,
    description:
        "Strict ring dips. Rings close, shoulders controlled, full lockout.",
    xpToUnlock: 900,
    baseXp: 16,
    xpPerRep: 6,
    xpPerSecond: 0,
    sortOrder: 6220,
  ),
  SeedMovement(
    id: "ring_turnout_dip",
    name: "Ring Dip (RTO Finish)",
    category: "rings",
    difficulty: 7,
    description:
        "Dip with rings turned out at lockout. Big step toward ring strength skills.",
    xpToUnlock: 1600,
    baseXp: 20,
    xpPerRep: 6,
    xpPerSecond: 0,
    sortOrder: 6230,
  ),
  SeedMovement(
    id: "ring_transition_low",
    name: "Ring Muscle-up Transition (Low Rings)",
    category: "rings",
    difficulty: 6,
    description:
        "Low rings drill. False grip, keep rings tight, smooth turnover.",
    xpToUnlock: 1200,
    baseXp: 16,
    xpPerRep: 3,
    xpPerSecond: 0,
    sortOrder: 6240,
  ),
  SeedMovement(
    id: "ring_muscle_up",
    name: "Ring Muscle-up",
    category: "rings",
    difficulty: 9,
    description: "False grip + strict transition. Huge milestone.",
    xpToUnlock: 2800,
    baseXp: 22,
    xpPerRep: 7,
    xpPerSecond: 0,
    sortOrder: 6250,
  ),
  SeedMovement(
    id: "ring_inverted_hang",
    name: "Ring Inverted Hang (Hold)",
    category: "rings",
    difficulty: 7,
    description: "Inverted hang on rings. Control and shoulder strength.",
    xpToUnlock: 1600,
    baseXp: 20,
    xpPerRep: 0,
    xpPerSecond: 5,
    sortOrder: 6260,
  ),
  SeedMovement(
    id: "ring_tuck_back_lever",
    name: "Ring Tuck Back Lever (Hold)",
    category: "rings",
    difficulty: 8,
    description:
        "Tuck back lever on rings. Active shoulders, glutes on, no pike.",
    xpToUnlock: 2100,
    baseXp: 22,
    xpPerRep: 0,
    xpPerSecond: 6,
    sortOrder: 6270,
  ),
  SeedMovement(
    id: "ring_back_lever",
    name: "Ring Back Lever (Hold)",
    category: "rings",
    difficulty: 9,
    description: "Full back lever on rings. Shoulder extension + body tension.",
    xpToUnlock: 2800,
    baseXp: 26,
    xpPerRep: 0,
    xpPerSecond: 7,
    sortOrder: 6280,
  ),
  SeedMovement(
    id: "ring_cross_lean",
    name: "Ring Cross Lean (Hold)",
    category: "rings",
    difficulty: 9,
    description:
        "Lean toward cross with minimal bend. Tendon prep for assisted cross.",
    xpToUnlock: 2800,
    baseXp: 26,
    xpPerRep: 0,
    xpPerSecond: 7,
    sortOrder: 6290,
  ),
  SeedMovement(
    id: "ring_assisted_iron_cross",
    name: "Assisted Iron Cross (Bands)",
    category: "rings",
    difficulty: 9,
    description:
        "Band-assisted cross holds. Build tendon/shoulder strength safely.",
    xpToUnlock: 2800,
    baseXp: 26,
    xpPerRep: 0,
    xpPerSecond: 7,
    sortOrder: 6300,
  ),
  SeedMovement(
    id: "iron_cross",
    name: "Iron Cross (Rings)",
    category: "rings",
    difficulty: 10,
    description: "Full iron cross hold. Extreme ring strength.",
    xpToUnlock: 4200,
    baseXp: 32,
    xpPerRep: 0,
    xpPerSecond: 10,
    sortOrder: 6310,
  ),
  SeedMovement(
    id: "assisted_maltese",
    name: "Assisted Maltese (Bands)",
    category: "rings",
    difficulty: 10,
    description:
        "Band-assisted maltese holds. Extremely demandingâ€”progress slowly.",
    xpToUnlock: 5200,
    baseXp: 34,
    xpPerRep: 0,
    xpPerSecond: 10,
    sortOrder: 6320,
  ),
  SeedMovement(
    id: "maltese",
    name: "Maltese (Rings)",
    category: "rings",
    difficulty: 10,
    description: "Full maltese hold. Elite ring strength.",
    xpToUnlock: 6500,
    baseXp: 40,
    xpPerRep: 0,
    xpPerSecond: 12,
    sortOrder: 6330,
  ),

  // Rings accessories (optional / XP)
  SeedMovement(
    id: "ring_biceps_curl",
    name: "Ring Biceps Curl",
    category: "rings",
    difficulty: 3,
    description:
        "Bodyweight curl on rings. Keep elbows high and control the eccentric.",
    xpToUnlock: 250,
    baseXp: 10,
    xpPerRep: 4,
    xpPerSecond: 0,
    sortOrder: 6400,
  ),
  SeedMovement(
    id: "ring_triceps_extension",
    name: "Ring Triceps Extension",
    category: "rings",
    difficulty: 3,
    description: "Triceps extensions on rings. Keep elbows in and go slow.",
    xpToUnlock: 250,
    baseXp: 10,
    xpPerRep: 4,
    xpPerSecond: 0,
    sortOrder: 6410,
  ),
  SeedMovement(
    id: "ring_fly",
    name: "Ring Fly (Assisted)",
    category: "rings",
    difficulty: 4,
    description:
        "Assisted chest fly. Keep shoulders packed; do not overstretch.",
    xpToUnlock: 450,
    baseXp: 12,
    xpPerRep: 4,
    xpPerSecond: 0,
    sortOrder: 6420,
  ),
  SeedMovement(
    id: "ring_support_swings",
    name: "Ring Support Swings",
    category: "rings",
    difficulty: 3,
    description:
        "Small controlled swings in support. Teaches stability under motion.",
    xpToUnlock: 250,
    baseXp: 10,
    xpPerRep: 0,
    xpPerSecond: 2,
    sortOrder: 6430,
  ),
  SeedMovement(
    id: "ring_external_rotation",
    name: "Ring External Rotation",
    category: "rings",
    difficulty: 2,
    description:
        "Light shoulder health drill on rings/band. Slow and pain-free.",
    xpToUnlock: 150,
    baseXp: 8,
    xpPerRep: 2,
    xpPerSecond: 0,
    sortOrder: 6440,
  ),
];

const List<SeedPrereq> seedPrereqs = [
  // Mobility chains
  SeedPrereq(
    movementId: "pancake_stretch",
    prereqMovementId: "hamstring_mobility",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "pancake_stretch",
    prereqMovementId: "hip_flexor_mobility",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "couch_stretch",
    prereqMovementId: "hip_flexor_mobility",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "bridge_prep",
    prereqMovementId: "thoracic_extension",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "bridge_prep",
    prereqMovementId: "shoulder_dislocates",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "bridge",
    prereqMovementId: "bridge_prep",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "cossack_squat_mobility",
    prereqMovementId: "hamstring_mobility",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "cossack_squat_mobility",
    prereqMovementId: "ankle_mobility",
    prereqType: "unlocked",
  ),

  // Core
  SeedPrereq(
    movementId: "side_plank",
    prereqMovementId: "plank",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "hollow_hold",
    prereqMovementId: "plank",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "arch_hold",
    prereqMovementId: "plank",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "hanging_knee_raise",
    prereqMovementId: "hollow_hold",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "hanging_leg_raise",
    prereqMovementId: "hanging_knee_raise",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "toes_to_bar",
    prereqMovementId: "hanging_leg_raise",
    prereqType: "progress",
  ),

  SeedPrereq(
    movementId: "tuck_l_sit",
    prereqMovementId: "hollow_hold",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "l_sit",
    prereqMovementId: "tuck_l_sit",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "v_sit",
    prereqMovementId: "l_sit",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "v_sit",
    prereqMovementId: "pancake_stretch",
    prereqType: "unlocked",
  ),

  SeedPrereq(
    movementId: "hanging_oblique_raise",
    prereqMovementId: "hanging_knee_raise",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "hanging_windshield_wiper",
    prereqMovementId: "hanging_leg_raise",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "hanging_windshield_wiper",
    prereqMovementId: "side_plank",
    prereqType: "progress",
  ),

  // Dragon flag
  SeedPrereq(
    movementId: "tuck_dragon_flag",
    prereqMovementId: "hollow_hold",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "tuck_dragon_flag",
    prereqMovementId: "arch_hold",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "dragon_flag_negative",
    prereqMovementId: "tuck_dragon_flag",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "dragon_flag",
    prereqMovementId: "dragon_flag_negative",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "dragon_flag",
    prereqMovementId: "hanging_leg_raise",
    prereqType: "progress",
  ),

  // Compression for press
  SeedPrereq(
    movementId: "pike_compression",
    prereqMovementId: "hamstring_mobility",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "seated_pike_lift",
    prereqMovementId: "pike_compression",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "seated_pike_lift",
    prereqMovementId: "hollow_hold",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "straddle_compression",
    prereqMovementId: "pancake_stretch",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "straddle_compression",
    prereqMovementId: "l_sit",
    prereqType: "progress",
  ),

  // Push chain
  SeedPrereq(
    movementId: "knee_push_up",
    prereqMovementId: "incline_push_up",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "push_up",
    prereqMovementId: "knee_push_up",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "diamond_push_up",
    prereqMovementId: "push_up",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "decline_push_up",
    prereqMovementId: "push_up",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "archer_push_up",
    prereqMovementId: "decline_push_up",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "pseudo_planche_push_up",
    prereqMovementId: "archer_push_up",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "pseudo_planche_push_up",
    prereqMovementId: "wrist_mobility",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "pseudo_planche_push_up",
    prereqMovementId: "hollow_hold",
    prereqType: "progress",
  ),

  SeedPrereq(
    movementId: "support_hold",
    prereqMovementId: "push_up",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "parallel_dip",
    prereqMovementId: "support_hold",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "parallel_dip",
    prereqMovementId: "diamond_push_up",
    prereqType: "progress",
  ),

  SeedPrereq(
    movementId: "pike_push_up",
    prereqMovementId: "push_up",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "elevated_pike_push_up",
    prereqMovementId: "pike_push_up",
    prereqType: "progress",
  ),

  // Pull chain
  SeedPrereq(
    movementId: "scap_pull_up",
    prereqMovementId: "active_hang",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "australian_pull_up",
    prereqMovementId: "active_hang",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "negative_pull_up",
    prereqMovementId: "australian_pull_up",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "chin_up",
    prereqMovementId: "negative_pull_up",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "pull_up",
    prereqMovementId: "chin_up",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "explosive_pull_up",
    prereqMovementId: "pull_up",
    prereqType: "progress",
  ),

  // One-arm pull-up progression prereqs
  SeedPrereq(
    movementId: "archer_pull_up",
    prereqMovementId: "pull_up",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "typewriter_pull_up",
    prereqMovementId: "archer_pull_up",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "uneven_pull_up",
    prereqMovementId: "typewriter_pull_up",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "one_arm_hang",
    prereqMovementId: "active_hang",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "one_arm_hang",
    prereqMovementId: "scap_pull_up",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "one_arm_lockoff",
    prereqMovementId: "uneven_pull_up",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "one_arm_lockoff",
    prereqMovementId: "one_arm_hang",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "one_arm_negative_pull_up",
    prereqMovementId: "one_arm_lockoff",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "one_arm_pull_up",
    prereqMovementId: "one_arm_negative_pull_up",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "one_arm_pull_up",
    prereqMovementId: "pull_up",
    prereqType: "progress",
  ),

  // Legs
  SeedPrereq(
    movementId: "split_squat",
    prereqMovementId: "bodyweight_squat",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "reverse_lunge",
    prereqMovementId: "bodyweight_squat",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "bulgarian_split_squat",
    prereqMovementId: "split_squat",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "cossack_squat",
    prereqMovementId: "reverse_lunge",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "cossack_squat",
    prereqMovementId: "cossack_squat_mobility",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "jump_squat",
    prereqMovementId: "split_squat",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "shrimp_squat_negative",
    prereqMovementId: "bulgarian_split_squat",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "shrimp_squat",
    prereqMovementId: "bulgarian_split_squat",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "shrimp_squat",
    prereqMovementId: "shrimp_squat_negative",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "assisted_pistol_squat",
    prereqMovementId: "shrimp_squat",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "pistol_squat",
    prereqMovementId: "assisted_pistol_squat",
    prereqType: "progress",
  ),

  // Handstand / HSPU
  SeedPrereq(
    movementId: "wall_handstand",
    prereqMovementId: "wrist_mobility",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "wall_handstand",
    prereqMovementId: "elevated_pike_push_up",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "freestanding_handstand",
    prereqMovementId: "wall_handstand",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "wall_hspu_negative",
    prereqMovementId: "wall_handstand",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "wall_hspu_negative",
    prereqMovementId: "elevated_pike_push_up",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "wall_hspu",
    prereqMovementId: "wall_hspu_negative",
    prereqType: "progress",
  ),

  // Press handstand progression prereqs
  SeedPrereq(
    movementId: "tuck_press_handstand",
    prereqMovementId: "freestanding_handstand",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "tuck_press_handstand",
    prereqMovementId: "seated_pike_lift",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "straddle_press_handstand",
    prereqMovementId: "tuck_press_handstand",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "straddle_press_handstand",
    prereqMovementId: "straddle_compression",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "press_handstand",
    prereqMovementId: "straddle_press_handstand",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "press_handstand",
    prereqMovementId: "freestanding_handstand",
    prereqType: "progress",
  ),

  // Compound transition progression
  SeedPrereq(
    movementId: "l_sit_to_tuck_handstand",
    prereqMovementId: "l_sit",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "l_sit_to_tuck_handstand",
    prereqMovementId: "tuck_press_handstand",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "l_sit_to_handstand",
    prereqMovementId: "l_sit_to_tuck_handstand",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "l_sit_to_handstand",
    prereqMovementId: "press_handstand",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "v_sit_to_handstand",
    prereqMovementId: "l_sit_to_handstand",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "v_sit_to_handstand",
    prereqMovementId: "v_sit",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "l_sit_to_tuck_planche",
    prereqMovementId: "l_sit",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "l_sit_to_tuck_planche",
    prereqMovementId: "tuck_planche",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "tuck_planche_to_handstand",
    prereqMovementId: "l_sit_to_tuck_planche",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "tuck_planche_to_handstand",
    prereqMovementId: "tuck_press_handstand",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "tuck_planche_to_handstand",
    prereqMovementId: "adv_tuck_planche",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "l_sit_to_muscle_up_transition",
    prereqMovementId: "l_sit",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "l_sit_to_muscle_up_transition",
    prereqMovementId: "muscle_up_transition",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "l_sit_to_muscle_up_transition",
    prereqMovementId: "explosive_pull_up",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "front_lever_to_muscle_up",
    prereqMovementId: "l_sit_to_muscle_up_transition",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "front_lever_to_muscle_up",
    prereqMovementId: "front_lever",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "front_lever_to_muscle_up",
    prereqMovementId: "bar_muscle_up",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "bar_muscle_up_to_handstand_negative",
    prereqMovementId: "front_lever_to_muscle_up",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "bar_muscle_up_to_handstand_negative",
    prereqMovementId: "freestanding_handstand",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "bar_muscle_up_to_handstand_negative",
    prereqMovementId: "straddle_press_handstand",
    prereqType: "unlocked",
  ),

  // Lever line (holds)
  SeedPrereq(
    movementId: "tuck_front_lever",
    prereqMovementId: "pull_up",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "tuck_front_lever",
    prereqMovementId: "hollow_hold",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "adv_tuck_front_lever",
    prereqMovementId: "tuck_front_lever",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "straddle_front_lever",
    prereqMovementId: "adv_tuck_front_lever",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "front_lever",
    prereqMovementId: "straddle_front_lever",
    prereqType: "progress",
  ),

  // Lever raises
  SeedPrereq(
    movementId: "tuck_front_lever_raises",
    prereqMovementId: "tuck_front_lever",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "tuck_front_lever_raises",
    prereqMovementId: "hollow_hold",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "adv_tuck_front_lever_raises",
    prereqMovementId: "adv_tuck_front_lever",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "adv_tuck_front_lever_raises",
    prereqMovementId: "tuck_front_lever_raises",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "front_lever_raises",
    prereqMovementId: "front_lever",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "front_lever_raises",
    prereqMovementId: "adv_tuck_front_lever_raises",
    prereqType: "progress",
  ),

  // Back lever line
  SeedPrereq(
    movementId: "german_hang",
    prereqMovementId: "shoulder_dislocates",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "skin_the_cat",
    prereqMovementId: "german_hang",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "skin_the_cat",
    prereqMovementId: "active_hang",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "tuck_back_lever",
    prereqMovementId: "skin_the_cat",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "back_lever",
    prereqMovementId: "tuck_back_lever",
    prereqType: "progress",
  ),

  // Muscle-ups (bar)
  SeedPrereq(
    movementId: "muscle_up_transition",
    prereqMovementId: "explosive_pull_up",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "muscle_up_transition",
    prereqMovementId: "parallel_dip",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "bar_muscle_up",
    prereqMovementId: "muscle_up_transition",
    prereqType: "progress",
  ),

  // Human flag
  SeedPrereq(
    movementId: "flag_pole_support",
    prereqMovementId: "pull_up",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "flag_pole_support",
    prereqMovementId: "parallel_dip",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "flag_pole_support",
    prereqMovementId: "shoulder_dislocates",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "flag_pole_support",
    prereqMovementId: "hanging_windshield_wiper",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "tucked_human_flag",
    prereqMovementId: "flag_pole_support",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "adv_tuck_human_flag",
    prereqMovementId: "tucked_human_flag",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "straddle_human_flag",
    prereqMovementId: "adv_tuck_human_flag",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "human_flag",
    prereqMovementId: "straddle_human_flag",
    prereqType: "progress",
  ),

  // Planche
  SeedPrereq(
    movementId: "planche_lean",
    prereqMovementId: "wrist_mobility",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "planche_lean",
    prereqMovementId: "support_hold",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "planche_lean",
    prereqMovementId: "pseudo_planche_push_up",
    prereqType: "unlocked",
  ),

  SeedPrereq(
    movementId: "frog_stand",
    prereqMovementId: "wrist_mobility",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "frog_stand",
    prereqMovementId: "push_up",
    prereqType: "progress",
  ),

  SeedPrereq(
    movementId: "tuck_planche",
    prereqMovementId: "planche_lean",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "tuck_planche",
    prereqMovementId: "frog_stand",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "tuck_planche",
    prereqMovementId: "hollow_hold",
    prereqType: "progress",
  ),

  SeedPrereq(
    movementId: "adv_tuck_planche",
    prereqMovementId: "tuck_planche",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "straddle_planche",
    prereqMovementId: "adv_tuck_planche",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "straddle_planche",
    prereqMovementId: "shoulder_dislocates",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "planche",
    prereqMovementId: "straddle_planche",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "planche",
    prereqMovementId: "pseudo_planche_push_up",
    prereqType: "progress",
  ),

  // =========================
  // RINGS prereqs - EXPANDED
  // =========================
  SeedPrereq(
    movementId: "ring_support_assisted",
    prereqMovementId: "support_hold",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "ring_support_scap_shrugs",
    prereqMovementId: "ring_support_assisted",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "ring_support_hold",
    prereqMovementId: "ring_support_assisted",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "ring_support_hold",
    prereqMovementId: "ring_support_scap_shrugs",
    prereqType: "unlocked",
  ),

  SeedPrereq(
    movementId: "ring_row",
    prereqMovementId: "australian_pull_up",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "ring_face_pull",
    prereqMovementId: "ring_row",
    prereqType: "unlocked",
  ),

  SeedPrereq(
    movementId: "ring_push_up",
    prereqMovementId: "push_up",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "ring_pull_up",
    prereqMovementId: "pull_up",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "ring_pull_up",
    prereqMovementId: "ring_row",
    prereqType: "progress",
  ),

  SeedPrereq(
    movementId: "false_grip_hang",
    prereqMovementId: "active_hang",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "false_grip_row",
    prereqMovementId: "ring_row",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "false_grip_row",
    prereqMovementId: "false_grip_hang",
    prereqType: "unlocked",
  ),

  SeedPrereq(
    movementId: "ring_l_sit_support",
    prereqMovementId: "l_sit",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "ring_l_sit_support",
    prereqMovementId: "ring_support_hold",
    prereqType: "unlocked",
  ),

  SeedPrereq(
    movementId: "ring_support_turnout_assisted",
    prereqMovementId: "ring_support_hold",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "ring_support_rto",
    prereqMovementId: "ring_support_turnout_assisted",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "ring_support_rto",
    prereqMovementId: "support_hold",
    prereqType: "progress",
  ),

  SeedPrereq(
    movementId: "ring_dip_negative",
    prereqMovementId: "parallel_dip",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "ring_dip_negative",
    prereqMovementId: "ring_support_hold",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "ring_dip",
    prereqMovementId: "ring_dip_negative",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "ring_turnout_dip",
    prereqMovementId: "ring_dip",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "ring_turnout_dip",
    prereqMovementId: "ring_support_rto",
    prereqType: "unlocked",
  ),

  SeedPrereq(
    movementId: "ring_transition_low",
    prereqMovementId: "false_grip_row",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "ring_transition_low",
    prereqMovementId: "ring_turnout_dip",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "ring_muscle_up",
    prereqMovementId: "ring_transition_low",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "ring_muscle_up",
    prereqMovementId: "false_grip_hang",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "ring_muscle_up",
    prereqMovementId: "explosive_pull_up",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "ring_muscle_up",
    prereqMovementId: "ring_dip",
    prereqType: "progress",
  ),

  SeedPrereq(
    movementId: "ring_inverted_hang",
    prereqMovementId: "skin_the_cat",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "ring_tuck_back_lever",
    prereqMovementId: "ring_inverted_hang",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "ring_tuck_back_lever",
    prereqMovementId: "hollow_hold",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "ring_back_lever",
    prereqMovementId: "ring_tuck_back_lever",
    prereqType: "progress",
  ),

  SeedPrereq(
    movementId: "ring_cross_lean",
    prereqMovementId: "ring_support_rto",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "ring_cross_lean",
    prereqMovementId: "ring_back_lever",
    prereqType: "unlocked",
  ),

  SeedPrereq(
    movementId: "ring_assisted_iron_cross",
    prereqMovementId: "ring_cross_lean",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "ring_assisted_iron_cross",
    prereqMovementId: "shoulder_dislocates",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "ring_assisted_iron_cross",
    prereqMovementId: "ring_inverted_hang",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "iron_cross",
    prereqMovementId: "ring_assisted_iron_cross",
    prereqType: "progress",
  ),

  SeedPrereq(
    movementId: "assisted_maltese",
    prereqMovementId: "iron_cross",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "assisted_maltese",
    prereqMovementId: "planche_lean",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "maltese",
    prereqMovementId: "assisted_maltese",
    prereqType: "progress",
  ),
  SeedPrereq(
    movementId: "maltese",
    prereqMovementId: "iron_cross",
    prereqType: "progress",
  ),

  // Rings accessories (optional / XP)
  SeedPrereq(
    movementId: "ring_biceps_curl",
    prereqMovementId: "ring_row",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "ring_triceps_extension",
    prereqMovementId: "ring_support_hold",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "ring_fly",
    prereqMovementId: "ring_support_hold",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "ring_support_swings",
    prereqMovementId: "ring_support_assisted",
    prereqType: "unlocked",
  ),
  SeedPrereq(
    movementId: "ring_external_rotation",
    prereqMovementId: "shoulder_dislocates",
    prereqType: "unlocked",
  ),
];
